# Generated by Django 5.1.6 on 2025-03-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0003_alter_product_deleted_at_alter_user_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='quantity_product',
            field=models.IntegerField(default=1),
        ),
    ]
