# Generated by Django 5.1.6 on 2025-03-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0004_application_quantity_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pictures_url',
            field=models.ImageField(upload_to='WepAppLabs/WebApp/my_app1/static/pictures'),
        ),
    ]
