# Generated by Django 5.1.6 on 2025-03-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0005_alter_product_pictures_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pictures_url',
            field=models.ImageField(upload_to='C:\\pictures'),
        ),
    ]
