# Generated by Django 5.1.6 on 2025-03-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0006_alter_product_pictures_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pictures_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
