version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./WebApp:/app
    # env_file:
    #   - .env
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    restart: unless-stopped