# Generated by Django 5.1.6 on 2025-02-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deleted_at',
            field=models.DateField(default=None, null=True),
        ),
    ]
