# Generated by Django 5.2 on 2025-04-12 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('country', models.CharField(null=True)),
                ('pictures_url', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app1.category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_progress', models.BooleanField(default=False)),
                ('is_close', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_reject', models.BooleanField(default=False)),
                ('quantity_product', models.IntegerField(default=1)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app1.product')),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=16)),
                ('phone_number', models.CharField()),
                ('refresh_token', models.CharField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app1.category')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
