# Generated by Django 5.2 on 2025-04-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0005_alter_user_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=500, verbose_name='Пароль'),
        ),
    ]
