# Generated by Django 5.2 on 2025-04-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0006_alter_customuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
