# Generated by Django 5.2 on 2025-04-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0009_remove_user_username_user_is_admin_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_hash',
            new_name='password',
        ),
    ]
