# Generated by Django 5.2 on 2025-04-30 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0010_rename_password_hash_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
