# Generated by Django 5.2 on 2025-04-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0011_alter_basket_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
