# Generated by Django 5.2 on 2025-05-05 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0012_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='id_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app1.product'),
        ),
    ]
