# Generated by Django 5.2 on 2025-05-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0013_alter_application_id_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='list_application',
            field=models.JSONField(default=list),
        ),
    ]
