# Generated by Django 5.2 on 2025-05-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0014_customuser_list_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='quantity_product',
            field=models.IntegerField(),
        ),
    ]
