# Generated by Django 5.2 on 2025-06-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0016_alter_application_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='deleted_at',
            field=models.DateField(null=True),
        ),
    ]
