# Generated by Django 5.2 on 2025-06-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0017_alter_application_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
