# Generated by Django 5.2 on 2025-06-05 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0020_customuser_created_at_customuser_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
